---
pagetitle: ""
format: 
  revealjs: 
    theme: style.scss
    multiplex: true
    transition: fade
    height: 900
    width: 1600
    fontcolor: "#262d36"
    highlight-style: a11y
    code-line-numbers: false
editor: visual
---

##  {background-image="images/tapa.jpeg" aria-label="image with presentation title and user design."}


---

## Motivation

Learning Management Systems (LMS) for various objectives has become a key tool in education. A huge volume of student and teacher data is generated by LMS on a daily basis.

Transforming this data into relevant information for decision-making is a major challenge due to the complexity of the data structure and the difficulty of summarizing the learning process with registered information.
---

## Presentation objetives

- This talk focuses on statistical tools for the evaluation and monitoring of LMS use by students and teachers. First, a web application was developed as a tool that allows monitoring the use of educational platforms in a user-friendly manner.

- Additionally, statistical learning methods were used to predict students' performance in tests using LMS information as predictors. Challenges such as data structure and size present many hurdles in this project. Most of these challenges are addressed using efficient computational tools at each stage of data analysis.

---



Postgres serves as the SQL engine, data.table is used for data wrangling, and shiny, plotly, and ggplot2 are employed for communication and visualization. Finally, tidymodels and dbart are utilized for predictive models.




 